# ==========================================
# OrangeFox Config for Redmi K70 Pro (manet) - 14.1
# ==========================================

OF_MAINTAINER_PATCH_VERSION := 1
OF_MAINTAINER := XiaoBai
OF_MAINTAINER_AVATAR := /dev/null

# Screen: 1440×3200 中置打孔屏
OF_SCREEN_H := 3200
OF_STATUS_H := 120
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 2

# Core
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 0
OF_NO_RELOAD_MAGISKBOOT := 1
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_NO_MIUI_PATCH_WARNING := 1

# Crypto & Anti-brick
OF_SKIP_METADATA_DECRYPTION_WAIT := 0
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_KEEP_DM_VERITY := 1
OF_USE_MAGISKBOOT_COMPRESSED_WEBP := 0

# Partitions
OF_ENABLE_ALL_PARTITION_TOOLS := 1
OF_USE_DMCTL := 1

# OTA (MIUI)
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES := 1
OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR := 1
OF_DISABLE_MIUI_OTA_BY_DEFAULT := 0

# Misc
OF_ENABLE_LPTOOLS := 1
OF_QUICK_BACKUP_LIST := /boot;/data;
OF_PATCH_AVB20 := 1
